import type { Location } from "./map";

export const downloadOutput = (host: string, locationOutput: Location) => {
  const logId = `${host}_${crypto.randomUUID()}`;
  const logEntry = JSON.stringify({
    id: logId,
    timestamp: new Date().toISOString(),
    data: locationOutput
  }, null, 2);

  // Write to logs.txt
  const blob = new Blob([logEntry + '\n\n'], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${logId}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export const fenwickHk = [
  {
    ips: ["96.120.25.13"],
    latitude: 40.7128,
    longitude: -74.006,
    city: "New York",
    country: "US",
    facility: {
      id: 7267,
      org_id: 682,
      org_name: "Lumen Technologies Inc",
      campus_id: null,
      name: "Lumen New York",
      aka: "",
      name_long: "",
      website: "https://www.lumen.com/en-us/hybrid-it-cloud/data-centers.html",
      social_media: [
        {
          service: "website",
          identifier:
            "https://www.lumen.com/en-us/hybrid-it-cloud/data-centers.html",
        },
      ],
      clli: "NYCPNYYK",
      rencode: "",
      npanxx: "",
      notes: "",
      net_count: 4,
      ix_count: 0,
      sales_email: "",
      sales_phone: "",
      tech_email: "",
      tech_phone: "",
      available_voltage_services: [],
      diverse_serving_substations: null,
      property: "",
      region_continent: "North America",
      status_dashboard: "",
      logo: null,
      created: "2019-08-22T19:54:52Z",
      updated: "2025-09-26T22:53:13Z",
      status: "ok",
      address1: "601 W 26th St",
      address2: "",
      city: "New York",
      country: "US",
      state: "NY",
      zipcode: "10001-1101",
      floor: "",
      suite: "",
      latitude: 40.751657,
      longitude: -74.007158,
    },
    isp: "Comcast Cable Communications",
    source_cable: null,
    dest_cable: null,
    distance_to: 0,
    distance_from: 1157.118585692943,
  },
  {
    ips: ["96.110.167.177"],
    latitude: 41.885,
    longitude: -87.7845,
    city: "Oak Park",
    country: "US",
    facility: {
      id: 1730,
      org_id: 682,
      org_name: "Lumen Technologies Inc",
      campus_id: null,
      name: "Level(3) Chicago (Kingsbury)",
      aka: "",
      name_long: "",
      website: "http://www.level3.com",
      social_media: [
        {
          service: "website",
          identifier: "http://www.level3.com",
        },
      ],
      clli: "",
      rencode: "",
      npanxx: "",
      notes: "",
      net_count: 15,
      ix_count: 0,
      sales_email: "",
      sales_phone: "",
      tech_email: "",
      tech_phone: "",
      available_voltage_services: [],
      diverse_serving_substations: null,
      property: "",
      region_continent: "North America",
      status_dashboard: "",
      logo: null,
      created: "2014-02-06T00:00:00Z",
      updated: "2025-09-26T22:44:51Z",
      status: "ok",
      address1: "900 N Kingsbury St",
      address2: "",
      city: "Chicago",
      country: "US",
      state: "IL",
      zipcode: "60606",
      floor: "",
      suite: "",
      latitude: 41.898951,
      longitude: -87.644642,
    },
    isp: "Comcast Cable Communications, LLC",
    source_cable: null,
    dest_cable: null,
    distance_to: 1157.118585692943,
    distance_from: 208.00979980670985,
  },
  {
    ips: ["162.151.44.2", "69.139.185.93"],
    latitude: 40.4864,
    longitude: -86.1336,
    city: "Kokomo",
    country: "US",
    facility: null,
    isp: "Comcast Cable Communications, LLC",
    source_cable: null,
    dest_cable: null,
    distance_to: 208.00979980670985,
    distance_from: 292.66256631639556,
  },
  {
    ips: ["162.151.37.69", "96.110.43.21"],
    latitude: 40.6936,
    longitude: -89.589,
    city: "Peoria",
    country: "US",
    facility: {
      id: 1730,
      org_id: 682,
      org_name: "Lumen Technologies Inc",
      campus_id: null,
      name: "Level(3) Chicago (Kingsbury)",
      aka: "",
      name_long: "",
      website: "http://www.level3.com",
      social_media: [
        {
          service: "website",
          identifier: "http://www.level3.com",
        },
      ],
      clli: "",
      rencode: "",
      npanxx: "",
      notes: "",
      net_count: 15,
      ix_count: 0,
      sales_email: "",
      sales_phone: "",
      tech_email: "",
      tech_phone: "",
      available_voltage_services: [],
      diverse_serving_substations: null,
      property: "",
      region_continent: "North America",
      status_dashboard: "",
      logo: null,
      created: "2014-02-06T00:00:00Z",
      updated: "2025-09-26T22:44:51Z",
      status: "ok",
      address1: "900 N Kingsbury St",
      address2: "",
      city: "Chicago",
      country: "US",
      state: "IL",
      zipcode: "60606",
      floor: "",
      suite: "",
      latitude: 41.898951,
      longitude: -87.644642,
    },
    isp: "Comcast Cable Communications, LLC",
    source_cable: null,
    dest_cable: null,
    distance_to: 292.66256631639556,
    distance_from: 915.9579315670254,
  },
  {
    ips: ["96.110.32.86"],
    latitude: 39.0152,
    longitude: -77.4543,
    city: "Ashburn",
    country: "US",
    facility: {
      id: 1,
      org_id: 2,
      org_name: "Equinix, Inc.",
      campus_id: 14,
      name: "Equinix DC1-DC15, DC21 - Ashburn",
      aka: "",
      name_long: "",
      website: "http://www.equinix.com/",
      social_media: [
        {
          service: "website",
          identifier: "http://www.equinix.com/",
        },
      ],
      clli: "ASBNVA",
      rencode: "",
      npanxx: "703-723",
      notes: "",
      net_count: 500,
      ix_count: 8,
      sales_email: "",
      sales_phone: "",
      tech_email: "",
      tech_phone: "",
      available_voltage_services: [],
      diverse_serving_substations: null,
      property: null,
      region_continent: "North America",
      status_dashboard: null,
      logo: null,
      created: "2010-07-29T00:00:00Z",
      updated: "2025-09-26T22:42:02Z",
      status: "ok",
      address1: "21715 Filigree Ct",
      address2: "Building F",
      city: "Ashburn",
      country: "US",
      state: "VA",
      zipcode: "20147-6205",
      floor: "",
      suite: "",
      latitude: 39.016363,
      longitude: -77.459023,
    },
    isp: "Comcast Cable Communications, LLC",
    source_cable: null,
    dest_cable: null,
    distance_to: 915.9579315670254,
    distance_from: 3654.9292814780674,
  },
  {
    ips: ["63.223.43.114", "63.223.43.114"],
    latitude: 34.0549,
    longitude: -118.243,
    city: "Los Angeles",
    country: "US",
    facility: null,
    isp: "Gateway Communications",
    source_cable: null,
    dest_cable: null,
    distance_to: 3654.9292814780674,
    distance_from: 3935.5703207662664,
  },
  {
    ips: ["63.222.112.51"],
    latitude: 40.7128,
    longitude: -74.006,
    city: "New York",
    country: "US",
    facility: null,
    isp: "Gateway Communications",
    source_cable: null,
    dest_cable: null,
    distance_to: 3935.5703207662664,
    distance_from: 15499.04140145989,
  },
  {
    ips: ["103.200.15.68"],
    latitude: -27.4539,
    longitude: 153.033,
    city: "Fortitude Valley",
    country: "AU",
    facility: {
      id: 4688,
      org_id: 7093,
      org_name: "NEXTDC",
      campus_id: null,
      name: "NEXTDC B2",
      aka: "",
      name_long: "",
      website: "https://www.nextdc.com/data-centres/b2-brisbane-data-centre",
      social_media: [
        {
          service: "website",
          identifier:
            "https://www.nextdc.com/data-centres/b2-brisbane-data-centre",
        },
      ],
      clli: "",
      rencode: "",
      npanxx: "",
      notes: "",
      net_count: 80,
      ix_count: 3,
      sales_email: "",
      sales_phone: "",
      tech_email: "",
      tech_phone: "",
      available_voltage_services: [],
      diverse_serving_substations: null,
      property: null,
      region_continent: "Australia",
      status_dashboard: null,
      logo: null,
      created: "2017-12-01T15:41:07Z",
      updated: "2025-09-26T22:49:59Z",
      status: "ok",
      address1: "454 St. Pauls Terrace",
      address2: "",
      city: "Fortitude Valley",
      country: "AU",
      state: "QLD",
      zipcode: "4006",
      floor: "",
      suite: "",
      latitude: -27.453902,
      longitude: 153.0332,
    },
    isp: "SUPERLOOP (AUSTRALIA) PTY LTD",
    source_cable: {
      id: "hawaiki-nui-1",
      entry_point: {
        lat: -27.46888410816531,
        lon: 153.02282700000043,
      },
    },
    dest_cable: null,
    distance_to: 15499.04140145989,
    distance_from: 729.5097955310397,
  },
  {
    ips: ["150.107.73.53"],
    latitude: -33.8071,
    longitude: 151.1289,
    city: "Sydney",
    country: "AU",
    facility: {
      id: 1660,
      org_id: 7093,
      org_name: "NEXTDC",
      campus_id: null,
      name: "NEXTDC S1",
      aka: "",
      name_long: "",
      website: "http://www.nextdc.com",
      social_media: [
        {
          service: "website",
          identifier: "http://www.nextdc.com",
        },
      ],
      clli: "",
      rencode: "",
      npanxx: "",
      notes: "",
      net_count: 102,
      ix_count: 3,
      sales_email: "",
      sales_phone: "",
      tech_email: "",
      tech_phone: "",
      available_voltage_services: [],
      diverse_serving_substations: null,
      property: null,
      region_continent: "Australia",
      status_dashboard: null,
      logo: null,
      created: "2013-11-04T00:00:00Z",
      updated: "2025-09-26T22:44:44Z",
      status: "ok",
      address1: "4 Eden Park Drive",
      address2: "Macquarie Park",
      city: "Sydney",
      country: "AU",
      state: "NSW",
      zipcode: "2113",
      floor: "",
      suite: "",
      latitude: -33.785263,
      longitude: 151.13149,
    },
    isp: "Mammoth Media Pty Ltd",
    source_cable: null,
    dest_cable: {
      id: "hawaiki-nui-1",
      entry_point: {
        lat: -33.869695999999635,
        lon: 151.2070371188603,
      },
    },
    distance_to: 729.5097955310397,
    distance_from: 0,
  },
];

export const bbcCom = [
  {
    ips: ["96.120.25.13"],
    latitude: 40.7128,
    longitude: -74.006,
    city: "New York",
    country: "US",
    facility: {
      id: 7267,
      org_id: 682,
      org_name: "Lumen Technologies Inc",
      campus_id: null,
      name: "Lumen New York",
      aka: "",
      name_long: "",
      website: "https://www.lumen.com/en-us/hybrid-it-cloud/data-centers.html",
      social_media: [
        {
          service: "website",
          identifier:
            "https://www.lumen.com/en-us/hybrid-it-cloud/data-centers.html",
        },
      ],
      clli: "NYCPNYYK",
      rencode: "",
      npanxx: "",
      notes: "",
      net_count: 4,
      ix_count: 0,
      sales_email: "",
      sales_phone: "",
      tech_email: "",
      tech_phone: "",
      available_voltage_services: [],
      diverse_serving_substations: null,
      property: "",
      region_continent: "North America",
      status_dashboard: "",
      logo: null,
      created: "2019-08-22T19:54:52Z",
      updated: "2025-09-26T22:53:13Z",
      status: "ok",
      address1: "601 W 26th St",
      address2: "",
      city: "New York",
      country: "US",
      state: "NY",
      zipcode: "10001-1101",
      floor: "",
      suite: "",
      latitude: 40.751657,
      longitude: -74.007158,
    },
    isp: "Comcast Cable Communications",
    source_cable: null,
    dest_cable: null,
    distance_to: 0,
    distance_from: 1157.118585692943,
  },
  {
    ips: ["96.110.167.177", "24.153.88.109"],
    latitude: 41.885,
    longitude: -87.7845,
    city: "Oak Park",
    country: "US",
    facility: {
      id: 1730,
      org_id: 682,
      org_name: "Lumen Technologies Inc",
      campus_id: null,
      name: "Level(3) Chicago (Kingsbury)",
      aka: "",
      name_long: "",
      website: "http://www.level3.com",
      social_media: [
        {
          service: "website",
          identifier: "http://www.level3.com",
        },
      ],
      clli: "",
      rencode: "",
      npanxx: "",
      notes: "",
      net_count: 15,
      ix_count: 0,
      sales_email: "",
      sales_phone: "",
      tech_email: "",
      tech_phone: "",
      available_voltage_services: [],
      diverse_serving_substations: null,
      property: "",
      region_continent: "North America",
      status_dashboard: "",
      logo: null,
      created: "2014-02-06T00:00:00Z",
      updated: "2025-09-26T22:44:51Z",
      status: "ok",
      address1: "900 N Kingsbury St",
      address2: "",
      city: "Chicago",
      country: "US",
      state: "IL",
      zipcode: "60606",
      floor: "",
      suite: "",
      latitude: 41.898951,
      longitude: -87.644642,
    },
    isp: "Comcast Cable Communications, LLC",
    source_cable: null,
    dest_cable: null,
    distance_to: 1157.118585692943,
    distance_from: 49.69274743180206,
  },
  {
    ips: ["68.87.232.70"],
    latitude: 41.5284,
    longitude: -87.4237,
    city: "Griffith",
    country: "US",
    facility: null,
    isp: "Comcast Cable Communications, LLC",
    source_cable: null,
    dest_cable: null,
    distance_to: 49.69274743180206,
    distance_from: 203.76699468029383,
  },
  {
    ips: ["162.151.37.69"],
    latitude: 40.6936,
    longitude: -89.589,
    city: "Peoria",
    country: "US",
    facility: {
      id: 1730,
      org_id: 682,
      org_name: "Lumen Technologies Inc",
      campus_id: null,
      name: "Level(3) Chicago (Kingsbury)",
      aka: "",
      name_long: "",
      website: "http://www.level3.com",
      social_media: [
        {
          service: "website",
          identifier: "http://www.level3.com",
        },
      ],
      clli: "",
      rencode: "",
      npanxx: "",
      notes: "",
      net_count: 15,
      ix_count: 0,
      sales_email: "",
      sales_phone: "",
      tech_email: "",
      tech_phone: "",
      available_voltage_services: [],
      diverse_serving_substations: null,
      property: "",
      region_continent: "North America",
      status_dashboard: "",
      logo: null,
      created: "2014-02-06T00:00:00Z",
      updated: "2025-09-26T22:44:51Z",
      status: "ok",
      address1: "900 N Kingsbury St",
      address2: "",
      city: "Chicago",
      country: "US",
      state: "IL",
      zipcode: "60606",
      floor: "",
      suite: "",
      latitude: 41.898951,
      longitude: -87.644642,
    },
    isp: "Comcast Cable Communications, LLC",
    source_cable: null,
    dest_cable: null,
    distance_to: 203.76699468029383,
    distance_from: 1403.3186609643492,
  },
  {
    ips: ["151.101.192.81"],
    latitude: 45.5019,
    longitude: -73.5674,
    city: "Montreal",
    country: "CA",
    facility: {
      id: 1945,
      org_id: 7030,
      org_name: "Cologix, Inc.",
      campus_id: null,
      name: "Cologix MTL7",
      aka: "",
      name_long: "",
      website: "http://www.cologix.com",
      social_media: [
        {
          service: "website",
          identifier: "http://www.cologix.com",
        },
      ],
      clli: "",
      rencode: "",
      npanxx: "",
      notes: "",
      net_count: 25,
      ix_count: 1,
      sales_email: "",
      sales_phone: "",
      tech_email: "",
      tech_phone: "",
      available_voltage_services: [],
      diverse_serving_substations: null,
      property: null,
      region_continent: "North America",
      status_dashboard: null,
      logo: null,
      created: "2014-10-22T00:00:00Z",
      updated: "2025-09-26T22:45:19Z",
      status: "ok",
      address1: "1155 University St.",
      address2: "",
      city: "Montreal",
      country: "CA",
      state: "",
      zipcode: "",
      floor: "",
      suite: "",
      latitude: 45.50234,
      longitude: -73.567788,
    },
    isp: "Fastly, Inc.",
    source_cable: null,
    dest_cable: null,
    distance_to: 1403.3186609643492,
    distance_from: 0,
  },
];

export const fenwickIps = [
  "10.0.0.1",
  "96.120.25.13",
  "96.110.167.177",
  "162.151.44.2",
  "69.139.185.93",
  "162.151.37.69",
  "96.110.43.25",
  "96.110.32.94",
  "63.223.43.114",
  "63.223.43.114",
  "63.222.112.51",
  "103.200.15.68",
  "27.122.122.10",
  "150.107.73.53",
];
